AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This cloudformation template launces an EC2 instance, with sg allowing 22,80. Installing Apache web server, serving a static website.
Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable 22, 80.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: alyssa-key-pair2
      ImageId: ami-0ed752ea0f62749af
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref WebSecurityGroup
      UserData: !Base64 |
        #! /bin/bash
        yum update -y
        yum install httpd -y
        FOLDER="https://raw.githubusercontent.com/bluehackrafestefano/Project-101-kittens-carousel-static-website-ec2-CF/main/static-web"
        cd /var/www/html
        wget ${FOLDER}/index.html
        wget ${FOLDER}/cat0.jpg
        wget ${FOLDER}/cat1.jpg
        wget ${FOLDER}/cat2.jpg
        wget ${FOLDER}/cat3.png
        wget ${FOLDER}/clarusway.png
        systemctl start httpd
        systemctl enable httpd
      Tags:
        - Key: Name
          Value: Alyssa-InstancefromCloudformation
Outputs:
  WebSiteDNSLink:
    Value: !Sub
      - http://${PublicAddress}
      - PublicAddress: !GetAtt EC2Instance.PublicDnsName
    Description: Aplication link.









